spring:
  application:
    name: producer-server
server:
  port: 10085


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:10081/eureka/
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 15000
