spring:
  application:
    name: web-server
server:
  port: 10083


# EUREKA ??
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:10081/eureka/
ribbon:
  #??????????????????????????????????
  ReadTimeout: 15000
  #????????????????????????
  ConnectTimeout: 15000
